name: Build and Deploy

on:
  push:
    branches:
      - main  # ou outra branch que você usa para deploy

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # ou a versão que você usa

      - name: Restaurar dependências
        run: dotnet restore ./pagina-inicial.sln  # ou o caminho correto do seu .sln

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publicar
        run: dotnet publish --configuration Release --output ./publicado

      # Aqui você pode adicionar os passos de deploy para o Azure
